# Copyright (c) 2026 Arm Limited (or its affiliates). All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Build and Run on FVP Simulation
on:
  workflow_dispatch:
  pull_request:
    branches: [v3]
  push:
    branches: [v3]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: v3

      - name: Setup Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Python Requirements
        run: pip install -r requirements.txt
      
      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./vcpkg-configuration.json"
          cache: "ModelNova"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1


      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Cache downloaded packs
        uses: actions/cache@v5
        with:
          key: ModelNova
          path: /home/runner/.cache/arm/packs/.Download

      - name: Add Beta packs
        working-directory: ./
        run: |
          cpackget add ./packs/PyTorch.ExecuTorch.1.1.0-rc1-build.12/PyTorch.ExecuTorch.pdsc --agree-embedded-license
          cpackget add ./packs/AlifSemiconductor.Ensemble.2.2.0-dev8+g560eb47.pack --agree-embedded-license

      - name: Build the target-set
        working-directory: ./RockPaperScissors/AppKit-E8_USB
        run: |
          cbuild SDS.csolution.yml --active SSE-320-U85 --packs

      - name: Run on FVP
        working-directory: ./RockPaperScissors/AppKit-E8_USB
        run: |
          FVP_Corstone_SSE-320 -f ./Board/Corstone-320/fvp_config.txt -a ./out/AlgorithmTest/SSE-320-U85/Debug/AlgorithmTest.axf --simlimit 12 || true

      - name: Print log file of the FVP VSI3 SDSIO service
        working-directory: ./RockPaperScissors/AppKit-E8_USB
        run: |
          cat "./algorithm/SDS Recordings/sdsio.log"

      - name: Upload output of the built target-set
        uses: actions/upload-artifact@v7
        with:
          name: RPS_SSE-320-U85_FVP
          path: |
            ./RockPaperScissors/AppKit-E8_USB/out
            ./RockPaperScissors/AppKit-E8_USB/algorithm/SDS Recordings/*.p.sds
            ./RockPaperScissors/AppKit-E8_USB/algorithm/SDS Recordings/sdsio.log
